ip: localhost
drones:
    d1:
        init_path: paths/small_square_street/semi/init1.txt
        main_path: paths/small_square_street/semi/steps1.txt
        velocity: 1
        output_dir: output/d1
        auto_rotation: false
    d2:
        init_path: paths/small_square_street/semi/init2.txt
        main_path: paths/small_square_street/semi/steps2.txt
        velocity: 1
        output_dir: output/d2
        auto_rotation: false
